name: Bug report
description: Report a reproducible bug in the SDK
title: "bug: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug! Please include the details below so we can reproduce and fix it quickly.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - packages/js (@unilic/client)
        - packages/react (@unilic/react)
        - packages/php
        - packages/core (@unilic/core)
        - docs
        - other / not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which SDK version(s) are you using?
      placeholder: e.g. 0.1.0
    validations:
      required: false

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime / framework
      options:
        - Browser
        - Node.js
        - Next.js
        - Vite
        - React
        - PHP
        - Laravel
        - WordPress
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Steps + smallest code snippet that reproduces the issue.
      placeholder: |
        1. Configure client with ...
        2. Call ...
        3. Observe ...

        ```ts
        // minimal snippet
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / errors
      description: Paste stack traces or error output (remove secrets).
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn’t find a duplicate
          required: true
        - label: I removed any API keys / tokens from logs and snippets
          required: true
